[project]
site_name = "emcham.io"
site_description = "EDWARD McHAM | Senior Technical Writer / Documentation Engineer"
site_author = "Edward McHam"
site_url = "https://edwardmcham.github.io/"
nav = [
    { "Blog" = "index.md" },
    { "Resume" = "resume.md" },
    { "Portfolio" = "portfolio.md" },
]
extra_css = [
    "stylesheets/glightbox.min.css",
    "stylesheets/extra.css",
]
extra_javascript = [
    "javascripts/glightbox.min.js",
    "javascripts/extra.js",
]

[project.theme]
features = [
  "navigation.tabs",
  "navigation.sections",
  "navigation.top",
  "search.highlight",
  "toc.follow",
  "navigation.footer"
]
favicon = "assets/favicon.png"
custom_dir = "overrides"

[project.theme.font]
text = "Montserrat"
code = "JetBrains Mono"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[[project.extra.social]]
icon = "fontawesome/solid/envelope"
link = ""
name = "Email Eddie »"

[[project.extra.social]]
icon = "fontawesome/solid/phone"
link = "tel:+19034311974"
name = "Call Eddie »"

[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/in/edwardmcham/"
name = "Eddie on LinkedIn »"

[[project.extra.social]]
icon = "fontawesome/solid/globe"
link = "https://emcham.io"
name = "Website »"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/edwardmcham"
name = "Eddie on GitHub »"

[[project.extra.social]]
icon = "fontawesome/brands/youtube"
link = "https://www.youtube.com/@emcham-io"
name = "Eddie on YouTube »"

[[project.extra.social]]
icon = "fontawesome/solid/file-pdf"
link = "assets/RESUME_EDWARD_McHAM_Senior_Technical_Writer_Documentation_Engineer.pdf"
name = "Download PDF resume »"

[project.extra]
site_author_email = "edward.mcham@gmail.com"

[project.markdown_extensions.pymdownx.snippets]
base_path = ["includes"]
check_paths = true

[project.markdown_extensions.md_in_html]

[project.markdown_extensions.zensical.extensions.glightbox]
auto = false
width = "600px"
height = "auto"

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.zensical.extensions.macros]
render_by_default = true